// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozuhrmvthevczxxbltnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96dWhybXZ0aGV2Y3p4eGJsdG5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MTQ1NTgsImV4cCI6MjA2Mjk5MDU1OH0.Ei2DyFxRrqonuAdIj5yph9QQX_hyvP-Xeob5ml5UnIQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);